// Bundles maps/scripts/point_script sources out of src/ into the plain .js
// files that the point_script entities in Hammer actually reference
// (maps/scripts/melon_drive.js, maps/scripts/gamemode.js). Hammer compiles
// those files to .vjs_c itself at map build/load time — it does not resolve
// local imports — so this is the step that turns a multi-file src/<entry>/
// tree back into the single file each point_script entity expects.
//
// "cs_script/point_script" is a virtual module the CS2 engine provides at
// runtime, not an npm package, so it's marked external: Rollup leaves that
// one import statement untouched instead of trying to resolve/inline it.
//
// Rollup (not esbuild) on purpose: esbuild's bundler drops all regular
// comments (keeps only @license/@preserve ones) even without minification,
// which would gut this codebase's explanatory "why" comments in the file
// Hammer actually compiles. Rollup preserves them by default.
//
// Usage: node build.mjs [--watch]

import { rollup, watch as rollupWatch } from "rollup";
import { fileURLToPath } from "node:url";
import path from "node:path";

const rootDir = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(rootDir, "maps", "scripts");
const watch = process.argv.includes("--watch");

/** entry name -> source entry point. Add new point_script entities here. */
const entries = {
    melon_drive: path.join(rootDir, "src", "melon_drive", "index.js"),
    gamemode: path.join(rootDir, "src", "gamemode", "index.js"),
};

const external = ["cs_script/point_script"];

/** @param {string} name */
function outputOptionsFor(name) {
    return {
        file: path.join(outDir, `${name}.js`),
        format: /** @type {const} */ ("es"),
        banner: `// AUTO-GENERATED by \`npm run build\` from src/${name}/ — do not edit directly.`,
    };
}

// Each entry is the whole program for its point_script entity, not a
// library with unused exports to prune, so tree-shaking has nothing
// useful to remove — it only risks rewriting constant-folded branches
// (e.g. `if (DEBUG)`) away from what the source actually says. Disabled
// to keep the shipped file a predictable, near-literal reflection of src/.
const treeshake = false;

async function buildOnce() {
    for (const [name, entryPoint] of Object.entries(entries)) {
        const bundle = await rollup({ input: entryPoint, external, treeshake });
        await bundle.write(outputOptionsFor(name));
        await bundle.close();
        console.log(`built maps/scripts/${name}.js`);
    }
}

function watchAll() {
    const watcher = rollupWatch(
        Object.entries(entries).map(([name, entryPoint]) => ({
            input: entryPoint,
            external,
            treeshake,
            output: outputOptionsFor(name),
        }))
    );
    watcher.on("event", (event) => {
        if (event.code === "BUNDLE_END") {
            console.log(`rebuilt ${path.basename(event.output[0])}`);
        } else if (event.code === "ERROR") {
            console.error(event.error);
        }
    });
    console.log("rollup: watching src/ for changes (Ctrl+C to stop)...");
}

if (watch) {
    watchAll();
} else {
    await buildOnce();
}
