// AUTO-GENERATED by tools/make-route-icons.mjs from the route prefabs' file
// names — re-run it after adding or renaming a route, don't hand-edit.
// Track id -> the name the hub window shows for it.
/** @type {Record<number, string>} */
export const ROUTE_NAMES = {
    1: "Canals",
    2: "Bridge",
    3: "Side Slice"
};
